"""
models/policy_models.py — Policy document data models for Nexus AI Governance Platform.

Covers:
  - PolicyDocument  : uploaded policy file with metadata
  - PolicyChunk     : a single chunk of a policy document (for RAG)
  - PolicyAnalysis  : gap analysis result
  - PolicyVersion   : versioned policy document comparison

Usage:
    from models.policy_models import PolicyDocument, PolicyAnalysis

    doc = PolicyDocument(
        name="privacy_policy_v2.pdf",
        text="We process personal data for...",
        framework="GDPR",
    )
    print(doc.word_count)
    print(doc.has_pii)
"""
from __future__ import annotations

import datetime
import uuid
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator


class PolicyDocument(BaseModel):
    """
    An uploaded or ingested policy document with metadata.

    Stored in session state as st.session_state["uploaded_docs"].
    """

    id:         str = Field(default_factory=lambda: str(uuid.uuid4())[:12])
    name:       str = Field(description="File name or user-provided title.")
    text:       str = Field(description="Full extracted text content.")
    framework:  str = Field(default="GDPR", description="Primary compliance framework.")
    source:     str = Field(default="upload", description="'upload' | 'paste' | 'api'")
    created_at: str = Field(
        default_factory=lambda: datetime.datetime.now().isoformat()[:19]
    )
    tags:       List[str] = Field(default_factory=list)
    metadata:   Dict[str, Any] = Field(default_factory=dict)

    # Pre-computed scan results (filled after upload)
    pii_detected:    Dict[str, List[str]] = Field(default_factory=dict)
    injection_risk:  float = Field(default=0.0, ge=0.0, le=1.0)
    is_flagged:      bool  = Field(default=False)

    model_config = {"extra": "ignore"}

    # ── Validators ────────────────────────────────────────────────────────────

    @field_validator("name", mode="before")
    @classmethod
    def clean_name(cls, v: Any) -> str:
        return str(v).strip() or "Untitled Document"

    @field_validator("injection_risk", mode="before")
    @classmethod
    def clamp_risk(cls, v: Any) -> float:
        try:
            return max(0.0, min(1.0, float(v)))
        except (TypeError, ValueError):
            return 0.0

    # ── Computed properties ───────────────────────────────────────────────────

    @property
    def word_count(self) -> int:
        return len(self.text.split())

    @property
    def char_count(self) -> int:
        return len(self.text)

    @property
    def has_pii(self) -> bool:
        return bool(self.pii_detected)

    @property
    def pii_types(self) -> List[str]:
        return list(self.pii_detected.keys())

    @property
    def is_safe(self) -> bool:
        return self.injection_risk < 0.5 and not self.is_flagged

    @property
    def preview(self) -> str:
        """First 300 chars for display."""
        return self.text[:300] + ("…" if len(self.text) > 300 else "")

    @property
    def file_ext(self) -> str:
        """Return file extension (e.g. '.pdf')."""
        if "." in self.name:
            return "." + self.name.rsplit(".", 1)[-1].lower()
        return ".txt"

    # ── Utility ───────────────────────────────────────────────────────────────

    def to_summary_dict(self) -> Dict[str, Any]:
        """Flat dict for display in upload page table."""
        return {
            "Name":           self.name,
            "Framework":      self.framework,
            "Words":          f"{self.word_count:,}",
            "PII":            f"⚠️ {len(self.pii_types)} type(s)" if self.has_pii else "✅ Clean",
            "Injection Risk": f"⚠️ {self.injection_risk:.0%}" if self.injection_risk > 0.3 else "✅ Safe",
            "Uploaded":       self.created_at[:10],
        }

    def __str__(self) -> str:
        return f"PolicyDocument({self.name!r}, {self.word_count} words, framework={self.framework})"


class PolicyChunk(BaseModel):
    """
    A single text chunk of a policy document, ready for vector store ingestion.
    Generated by rag/chunking.py and stored in the vector store.
    """
    id:        str = Field(default_factory=lambda: str(uuid.uuid4())[:12])
    doc_id:    str = Field(description="Parent PolicyDocument ID.")
    text:      str = Field(description="Chunk text content.")
    title:     str = Field(default="")
    framework: str = Field(default="GDPR")
    source:    str = Field(default="")
    chunk_idx: int = Field(default=0, description="Position in parent document.")
    citation:  str = Field(default="")
    tags:      List[str] = Field(default_factory=list)

    model_config = {"extra": "ignore"}

    @property
    def word_count(self) -> int:
        return len(self.text.split())


class PolicyAnalysis(BaseModel):
    """
    Result of a policy gap analysis performed by PolicyAnalysisAgent.

    Contains coverage score, present/missing elements, and AI analysis text.
    """
    doc_name:          str
    framework:         str
    coverage_score:    float = Field(ge=0.0, le=100.0, description="% of required elements present.")
    present_elements:  List[str] = Field(default_factory=list)
    missing_elements:  List[str] = Field(default_factory=list)
    missing_details:   List[Dict[str, Any]] = Field(default_factory=list)
    analysis:          str = Field(default="", description="LLM-generated gap analysis text.")
    recommendation:    str = Field(default="")
    created_at:        str = Field(
        default_factory=lambda: datetime.datetime.now().isoformat()[:19]
    )

    model_config = {"extra": "ignore"}

    @property
    def grade(self) -> str:
        """Letter grade based on coverage score."""
        if self.coverage_score >= 95: return "A+"
        if self.coverage_score >= 90: return "A"
        if self.coverage_score >= 80: return "B"
        if self.coverage_score >= 70: return "C"
        if self.coverage_score >= 60: return "D"
        return "F"

    @property
    def is_passing(self) -> bool:
        return self.coverage_score >= 60.0

    @property
    def gap_count(self) -> int:
        return len(self.missing_elements)

    def __str__(self) -> str:
        return (
            f"PolicyAnalysis({self.doc_name!r}, {self.framework}, "
            f"coverage={self.coverage_score:.0f}%, missing={self.gap_count})"
        )


class PolicyVersion(BaseModel):
    """
    A versioned snapshot of a policy document for comparison tracking.
    """
    doc_id:      str
    version:     str = Field(description="Version label, e.g. 'v1.0', 'v2.3-draft'.")
    name:        str
    text:        str
    framework:   str
    created_at:  str = Field(
        default_factory=lambda: datetime.datetime.now().isoformat()[:19]
    )
    created_by:  str = Field(default="")
    change_notes:str = Field(default="")

    model_config = {"extra": "ignore"}

    @property
    def word_count(self) -> int:
        return len(self.text.split())

    def summary(self) -> str:
        return (
            f"Version {self.version} of '{self.name}' "
            f"({self.word_count:,} words, {self.framework})"
        )


class GeneratedPolicySection(BaseModel):
    """
    A policy section drafted by the PolicyAnalysisAgent.
    """
    section_title: str
    framework:     str
    content:       str
    word_count:    int = 0
    created_at:    str = Field(
        default_factory=lambda: datetime.datetime.now().isoformat()[:19]
    )
    org_context:   str = Field(default="")

    model_config = {"extra": "ignore"}

    @field_validator("word_count", mode="before")
    @classmethod
    def compute_word_count(cls, v: Any, info: Any) -> int:
        if v and v > 0:
            return v
        # Try to compute from content if available
        try:
            content = info.data.get("content", "")
            return len(content.split())
        except Exception:
            return 0

    def __str__(self) -> str:
        return f"PolicySection({self.section_title!r}, {self.framework}, {self.word_count} words)"